version: "3"
services:
  db:
    image: postgres
    env_file:
      - env
    ports:
      - "54321:5432"
    networks:
      - postgresnetwork
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - webdata:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - postgresnetwork
networks:
    postgresnetwork:
        driver: bridge
volumes:
  dbdata:
  webdata: 